//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocketProgramming.Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWISS_table
    {
        public int Trip_ID { get; set; }
        public string Hotel_Name { get; set; }
        public string Hotel_trip_date { get; set; }
        public int Hotel_capasity { get; set; }
        public int Available_Room { get; set; }
    }
}
