//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocketProgramming.Airline
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEGASUS_table
    {
        public int trip_ID { get; set; }
        public string Airline_Name { get; set; }
        public string trip_date { get; set; }
        public int capasity { get; set; }
        public int available_Seats { get; set; }
    }
}
